package cse340.askforhelp;

import android.content.Intent;
import android.os.Bundle;
import android.text.method.LinkMovementMethod;
import android.view.View;
import android.widget.Button;
import android.widget.TextView;

/* ********************************************************************************************** *
 * ********************************************************************************************** *
 *                      DO NOT EDIT THIS FILE, PLEASE, DO NOT EDIT THIS FILE                      *
 * ********************************************************************************************** *
 * ********************************************************************************************** */

public class InfoActivity extends AbstractAFHActivity {

    /**
     * Callback that is called when the activity is first created.
     * @param savedInstanceState contains the activity's previously saved state
     */
    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_info);
        setVariables();
        setClickListeners();
    }

    /**
     * Set and store any variables needed by
     */
    protected void setVariables() {
        // Add support for clicking on a web link
        TextView link = findViewById(R.id.link);
        link.setMovementMethod(LinkMovementMethod.getInstance());
    }

    /**
     * Set up all of the click listeners for the objects on the screen
     */
    protected void setClickListeners() {
        super.setClickListeners();

        Button goToLicense = findViewById(R.id.buttonToLicense);
        goToLicense.setOnClickListener(new View.OnClickListener() {
            @Override
            public void onClick(View view) {
                Intent goToLicense = new Intent(view.getContext(), ApacheLicenseActivity.class);
                view.getContext().startActivity(goToLicense);
            }
        });
    }
}